#ifndef CDEFERRED_MANAGER_CLIENT_H
#define CDEFERRED_MANAGER_CLIENT_H

#include "cbase.h"

enum DEF_MATERIALS
{
	DEF_MAT_LIGHT_GLOBAL = 0,

	DEF_MAT_LIGHT_POINT_WORLD,
	DEF_MAT_LIGHT_POINT_FULLSCREEN,
	DEF_MAT_LIGHT_SPOT_WORLD,
	DEF_MAT_LIGHT_SPOT_FULLSCREEN,

	DEF_MAT_LIGHT_VOLUME_PREPASS,
	DEF_MAT_LIGHT_VOLUME_BLEND,
	DEF_MAT_LIGHT_VOLUME_POINT_WORLD,
	DEF_MAT_LIGHT_VOLUME_POINT_FULLSCREEN,
	DEF_MAT_LIGHT_VOLUME_SPOT_WORLD,
	DEF_MAT_LIGHT_VOLUME_SPOT_FULLSCREEN,

	DEF_MAT_LIGHT_RADIOSITY_GLOBAL,
	DEF_MAT_LIGHT_RADIOSITY_GLOBAL_1,
	DEF_MAT_LIGHT_RADIOSITY_GLOBAL_2,
	DEF_MAT_LIGHT_RADIOSITY_GLOBAL_3,
	DEF_MAT_LIGHT_RADIOSITY_SKY,
	DEF_MAT_LIGHT_RADIOSITY_SKY_1,
	DEF_MAT_LIGHT_RADIOSITY_SURFACE,
	DEF_MAT_LIGHT_RADIOSITY_SURFACE_1,
	DEF_MAT_LIGHT_RADIOSITY_VISIBILITY,
	DEF_MAT_LIGHT_RADIOSITY_VISIBILITY_1,
	DEF_MAT_LIGHT_RADIOSITY_FILTER,
	DEF_MAT_LIGHT_RADIOSITY_FILTER_1,
	DEF_MAT_LIGHT_RADIOSITY_FILTER_2,
	DEF_MAT_LIGHT_RADIOSITY_PROPAGATE_0,
	DEF_MAT_LIGHT_RADIOSITY_PROPAGATE_1,
	DEF_MAT_LIGHT_RADIOSITY_PROPAGATE_2,
	DEF_MAT_LIGHT_RADIOSITY_PROPAGATE_3,
	DEF_MAT_LIGHT_RADIOSITY_PROPAGATE_4,
	DEF_MAT_LIGHT_RADIOSITY_PROPAGATE_5,
	DEF_MAT_LIGHT_RADIOSITY_PROPAGATE_6,
	DEF_MAT_LIGHT_RADIOSITY_HIERARCHY_FIRST,
	DEF_MAT_LIGHT_RADIOSITY_HIERARCHY_COMBINED,
	DEF_MAT_LIGHT_RADIOSITY_HIERARCHY_10,
	DEF_MAT_LIGHT_RADIOSITY_HIERARCHY_5,
	DEF_MAT_LIGHT_RADIOSITY_SHADOW,
	DEF_MAT_LIGHT_RADIOSITY_BLEND,
	DEF_MAT_LIGHT_RADIOSITY_UPSAMPLE,

#if DEFCFG_DEFERRED_SHADING == 1
	DEF_MAT_SCREENSPACE_SHADING,
	DEF_MAT_SCREENSPACE_COMBINE,
#endif

	DEF_MAT_BLUR_G6_X,
	DEF_MAT_BLUR_G6_Y,

#ifdef DEBUG
	DEF_MAT_WIREFRAME_DEBUG,
#endif

	DEF_MAT_COUNT
};

class CDeferredManagerClient : public CAutoGameSystem
{
	typedef CAutoGameSystem BaseClass;
public:

	CDeferredManagerClient();
	~CDeferredManagerClient();

	virtual bool Init();
	virtual void Shutdown();

	inline bool IsDeferredRenderingEnabled();

	ImageFormat GetShadowDepthFormat();
	ImageFormat GetNullFormat();

	inline IMaterial *GetDeferredMaterial( DEF_MATERIALS mat );

private:

	bool m_bDefRenderingEnabled;

	void InitializeDeferredMaterials();
	void ShutdownDeferredMaterials();

	IMaterial *m_pMat_Def[ DEF_MAT_COUNT ];
	KeyValues *m_pKV_Def[ DEF_MAT_COUNT ];
};

bool CDeferredManagerClient::IsDeferredRenderingEnabled()
{
	return m_bDefRenderingEnabled;
}

IMaterial *CDeferredManagerClient::GetDeferredMaterial( DEF_MATERIALS mat )
{
	Assert( mat >= 0 && mat < DEF_MAT_COUNT );

	return m_pMat_Def[ mat ];
}

extern CDeferredManagerClient *GetDeferredManager();

#endif